### PR TITLE
Track db in git and embed data directly

### PR DESCRIPTION
**Pull request by kevinresol**
This does 2 things
1. track the `mime-db.json` file in git so that people can use this directly from github.
2. Instead of embedding the db as resource and parse at runtime, now it embeds the db as Haxe object directly. (this eliminates the base64 encoding overhead and runtime json parsing overhead)

### CODE REVIEW

**Comment by benmerckx** [comment]
I started with this approach (inline as haxe code, but more naive) however that would crash cpp and java. Cpp would just fail if I remember correctly and java had a limit to amount of code per file or something. We should get those back on travis first and see

**Comment by benmerckx** [comment]
Half of travis failures is probably because I started from nodejs language instead of haxe..

**Comment by kevinresol** [comment]
Yeah got code too large on java. but I think it deserves special handling.

**Comment by benmerckx** [comment]
True, we could keep resource for java/cpp and use your direct embed on other platforms

**Comment by benmerckx** [comment]
Just ran into this: https://mobile.twitter.com/mathias/status/1143551692732030979
Probably not relevant since resources are base64 encoded as well.

**Comment by kevinresol** [comment]
we can optimize for js

**Pull request merged**
